### PR TITLE
Add armv7 build

### PR DESCRIPTION
**Pull request by aalaesar**
## Description
- Allow to build kube-controller for armv7 architecture
- This is one of many PR for [armv7 support for calico](https://github.com/projectcalico/calico/issues/3583)
- Tests: CI tests locally

## Todos
- [ ] Tests
- [x] Release note

## Release Note
```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@aalaesar looks like this one needs a rebase... sorry :/

**Comment by marvin-tigera** [comment]
Removing "merge-when-ready" label due to new commits

**Pull request merged**
