### PR TITLE
Parameterize the docker hub org for the build image

### PR DESCRIPTION
**Pull request by jose-bigio**
Signed-off-by: jose-bigio <jose.bigio@docker.com>

## Description

Parameterize the docker hub org for the build image

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by tmjd** [comment]
LGTM

**Comment by caseydavenport** [comment]
@jose-bigio looks like this has gotten out of date - could you rebase?

**Comment by seemethere** [comment]
@caseydavenport is there any update on this?

**Comment by tmjd** [comment]
@tomdee  would you mind taking a look at this?

**Comment by tomdee** [comment]
@jose-bigio Do you really need this PR? Are you planning to make a similar change to the other repos?

Since you can already override the `CALICO_BUILD` variable I'm not sure what advantage this PR brings, so closing for now.

**Pull request closed without merging**
